language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t slazien/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true slazien/docker-react npm run test

  